In [2]:
import os

import numpy as np

import pandas as pd

In [3]:
PROJECT_DIR = r"C:\Users\Surface\Desktop\data-science-project\ML-Project\MLOps-Flight-Price-Prediction"
DATA_DIR = "notebook"

In [4]:
def get_data(name):
	file_name = f"{name}.csv"
	file_path = os.path.join(PROJECT_DIR, DATA_DIR, file_name)
	return pd.read_csv(file_path)

In [5]:
flights = get_data("flight_price")
flights

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [6]:
flights.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [7]:
import pymongo

In [8]:
# df should be converted into dict before we push it to mongodb

data = flights.to_dict(orient='records')

In [9]:
data

[{'Airline': 'IndiGo',
  'Date_of_Journey': '24/03/2019',
  'Source': 'Banglore',
  'Destination': 'New Delhi',
  'Route': 'BLR → DEL',
  'Dep_Time': '22:20',
  'Arrival_Time': '01:10 22 Mar',
  'Duration': '2h 50m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 3897},
 {'Airline': 'Air India',
  'Date_of_Journey': '1/05/2019',
  'Source': 'Kolkata',
  'Destination': 'Banglore',
  'Route': 'CCU → IXR → BBI → BLR',
  'Dep_Time': '05:50',
  'Arrival_Time': '13:15',
  'Duration': '7h 25m',
  'Total_Stops': '2 stops',
  'Additional_Info': 'No info',
  'Price': 7662},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '9/06/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → LKO → BOM → COK',
  'Dep_Time': '09:25',
  'Arrival_Time': '04:25 10 Jun',
  'Duration': '19h',
  'Total_Stops': '2 stops',
  'Additional_Info': 'No info',
  'Price': 13882},
 {'Airline': 'IndiGo',
  'Date_of_Journey': '12/05/2019',
  'Source': 'Kolkata',
  'Destination': 'Banglore',
  'Route': 'CCU → NAG → BLR',
  'Dep_Time': '18:05',
  'Arrival_Time': '23:30',
  'Duration': '5h 25m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 6218},
 {'Airline': 'IndiGo',
  'Date_of_Journey': '01/03/2019',
  'Source': 'Banglore',
  'Destination': 'New Delhi',
  'Route': 'BLR → NAG → DEL',
  'Dep_Time': '16:50',
  'Arrival_Time': '21:35',
  'Duration': '4h 45m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 13302},
 {'Airline': 'SpiceJet',
  'Date_of_Journey': '24/06/2019',
  'Source': 'Kolkata',
  'Destination': 'Banglore',
  'Route': 'CCU → BLR',
  'Dep_Time': '09:00',
  'Arrival_Time': '11:25',
  'Duration': '2h 25m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 3873},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '12/03/2019',
  'Source': 'Banglore',
  'Destination': 'New Delhi',
  'Route': 'BLR → BOM → DEL',
  'Dep_Time': '18:55',
  'Arrival_Time': '10:25 13 Mar',
  'Duration': '15h 30m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'In-flight meal not included',
  'Price': 11087},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '01/03/2019',
  'Source': 'Banglore',
  'Destination': 'New Delhi',
  'Route': 'BLR → BOM → DEL',
  'Dep_Time': '08:00',
  'Arrival_Time': '05:05 02 Mar',
  'Duration': '21h 5m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 22270},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '12/03/2019',
  'Source': 'Banglore',
  'Destination': 'New Delhi',
  'Route': 'BLR → BOM → DEL',
  'Dep_Time': '08:55',
  'Arrival_Time': '10:25 13 Mar',
  'Duration': '25h 30m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'In-flight meal not included',
  'Price': 11087},
 {'Airline': 'Multiple carriers',
  'Date_of_Journey': '27/05/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → BOM → COK',
  'Dep_Time': '11:25',
  'Arrival_Time': '19:15',
  'Duration': '7h 50m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 8625},
 {'Airline': 'Air India',
  'Date_of_Journey': '1/06/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → BLR → COK',
  'Dep_Time': '09:45',
  'Arrival_Time': '23:00',
  'Duration': '13h 15m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 8907},
 {'Airline': 'IndiGo',
  'Date_of_Journey': '18/04/2019',
  'Source': 'Kolkata',
  'Destination': 'Banglore',
  'Route': 'CCU → BLR',
  'Dep_Time': '20:20',
  'Arrival_Time': '22:55',
  'Duration': '2h 35m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 4174},
 {'Airline': 'Air India',
  'Date_of_Journey': '24/06/2019',
  'Source': 'Chennai',
  'Destination': 'Kolkata',
  'Route': 'MAA → CCU',
  'Dep_Time': '11:40',
  'Arrival_Time': '13:55',
  'Duration': '2h 15m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 4667},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '9/05/2019',
  'Source': 'Kolkata',
  'Destination': 'Banglore',
  'Route': 'CCU → BOM → BLR',
  'Dep_Time': '21:10',
  'Arrival_Time': '09:20 10 May',
  'Duration': '12h 10m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'In-flight meal not included',
  'Price': 9663},
 {'Airline': 'IndiGo',
  'Date_of_Journey': '24/04/2019',
  'Source': 'Kolkata',
  'Destination': 'Banglore',
  'Route': 'CCU → BLR',
  'Dep_Time': '17:15',
  'Arrival_Time': '19:50',
  'Duration': '2h 35m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 4804},
 {'Airline': 'Air India',
  'Date_of_Journey': '3/03/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → AMD → BOM → COK',
  'Dep_Time': '16:40',
  'Arrival_Time': '19:15 04 Mar',
  'Duration': '26h 35m',
  'Total_Stops': '2 stops',
  'Additional_Info': 'No info',
  'Price': 14011},
 {'Airline': 'SpiceJet',
  'Date_of_Journey': '15/04/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → PNQ → COK',
  'Dep_Time': '08:45',
  'Arrival_Time': '13:15',
  'Duration': '4h 30m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 5830},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '12/06/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → BOM → COK',
  'Dep_Time': '14:00',
  'Arrival_Time': '12:35 13 Jun',
  'Duration': '22h 35m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'In-flight meal not included',
  'Price': 10262},
 {'Airline': 'Air India',
  'Date_of_Journey': '12/06/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → CCU → BOM → COK',
  'Dep_Time': '20:15',
  'Arrival_Time': '19:15 13 Jun',
  'Duration': '23h',
  'Total_Stops': '2 stops',
  'Additional_Info': 'No info',
  'Price': 13381},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '27/05/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → BOM → COK',
  'Dep_Time': '16:00',
  'Arrival_Time': '12:35 28 May',
  'Duration': '20h 35m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'In-flight meal not included',
  'Price': 12898},
 {'Airline': 'GoAir',
  'Date_of_Journey': '6/03/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → BOM → COK',
  'Dep_Time': '14:10',
  'Arrival_Time': '19:20',
  'Duration': '5h 10m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 19495},
 {'Airline': 'Air India',
  'Date_of_Journey': '21/03/2019',
  'Source': 'Banglore',
  'Destination': 'New Delhi',
  'Route': 'BLR → COK → DEL',
  'Dep_Time': '22:00',
  'Arrival_Time': '13:20 19 Mar',
  'Duration': '15h 20m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 6955},
 {'Airline': 'IndiGo',
  'Date_of_Journey': '3/04/2019',
  'Source': 'Banglore',
  'Destination': 'Delhi',
  'Route': 'BLR → DEL',
  'Dep_Time': '04:00',
  'Arrival_Time': '06:50',
  'Duration': '2h 50m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 3943},
 {'Airline': 'IndiGo',
  'Date_of_Journey': '1/05/2019',
  'Source': 'Banglore',
  'Destination': 'Delhi',
  'Route': 'BLR → DEL',
  'Dep_Time': '18:55',
  'Arrival_Time': '21:50',
  'Duration': '2h 55m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 4823},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '6/05/2019',
  'Source': 'Kolkata',
  'Destination': 'Banglore',
  'Route': 'CCU → BOM → BLR',
  'Dep_Time': '18:55',
  'Arrival_Time': '08:15 07 May',
  'Duration': '13h 20m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'In-flight meal not included',
  'Price': 7757},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '9/06/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → IDR → BOM → COK',
  'Dep_Time': '21:25',
  'Arrival_Time': '12:35 10 Jun',
  'Duration': '15h 10m',
  'Total_Stops': '2 stops',
  'Additional_Info': 'No info',
  'Price': 13292},
 {'Airline': 'IndiGo',
  'Date_of_Journey': '1/06/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → LKO → COK',
  'Dep_Time': '21:50',
  'Arrival_Time': '03:35 02 Jun',
  'Duration': '5h 45m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 8238},
 {'Airline': 'GoAir',
  'Date_of_Journey': '15/05/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → BOM → COK',
  'Dep_Time': '07:00',
  'Arrival_Time': '12:55',
  'Duration': '5h 55m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 7682},
 {'Airline': 'Vistara',
  'Date_of_Journey': '18/06/2019',
  'Source': 'Banglore',
  'Destination': 'Delhi',
  'Route': 'BLR → DEL',
  'Dep_Time': '09:45',
  'Arrival_Time': '12:35',
  'Duration': '2h 50m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 4668},
 {'Airline': 'Vistara',
  'Date_of_Journey': '15/06/2019',
  'Source': 'Chennai',
  'Destination': 'Kolkata',
  'Route': 'MAA → CCU',
  'Dep_Time': '07:05',
  'Arrival_Time': '09:20',
  'Duration': '2h 15m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 3687},
 {'Airline': 'Vistara',
  'Date_of_Journey': '18/06/2019',
  'Source': 'Chennai',
  'Destination': 'Kolkata',
  'Route': 'MAA → CCU',
  'Dep_Time': '07:05',
  'Arrival_Time': '09:20',
  'Duration': '2h 15m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 3687},
 {'Airline': 'Air India',
  'Date_of_Journey': '1/05/2019',
  'Source': 'Kolkata',
  'Destination': 'Banglore',
  'Route': 'CCU → GAU → DEL → BLR',
  'Dep_Time': '09:50',
  'Arrival_Time': '23:15',
  'Duration': '13h 25m',
  'Total_Stops': '2 stops',
  'Additional_Info': 'No info',
  'Price': 13227},
 {'Airline': 'IndiGo',
  'Date_of_Journey': '6/04/2019',
  'Source': 'Banglore',
  'Destination': 'Delhi',
  'Route': 'BLR → DEL',
  'Dep_Time': '04:00',
  'Arrival_Time': '06:50',
  'Duration': '2h 50m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 4423},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '15/06/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → NAG → BOM → COK',
  'Dep_Time': '14:35',
  'Arrival_Time': '12:35 16 Jun',
  'Duration': '22h',
  'Total_Stops': '2 stops',
  'Additional_Info': 'In-flight meal not included',
  'Price': 10919},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '18/05/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → BOM → COK',
  'Dep_Time': '07:05',
  'Arrival_Time': '12:35',
  'Duration': '5h 30m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'In-flight meal not included',
  'Price': 12373},
 {'Airline': 'IndiGo',
  'Date_of_Journey': '27/06/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → BOM → COK',
  'Dep_Time': '10:35',
  'Arrival_Time': '21:00',
  'Duration': '10h 25m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 5894},
 {'Airline': 'SpiceJet',
  'Date_of_Journey': '21/05/2019',
  'Source': 'Kolkata',
  'Destination': 'Banglore',
  'Route': 'CCU → MAA → BLR',
  'Dep_Time': '15:05',
  'Arrival_Time': '20:20',
  'Duration': '5h 15m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 4649},
 {'Airline': 'Air India',
  'Date_of_Journey': '18/05/2019',
  'Source': 'Kolkata',
  'Destination': 'Banglore',
  'Route': 'CCU → BLR',
  'Dep_Time': '14:15',
  'Arrival_Time': '16:45',
  'Duration': '2h 30m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 6245},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '06/03/2019',
  'Source': 'Banglore',
  'Destination': 'New Delhi',
  'Route': 'BLR → BOM → DEL',
  'Dep_Time': '07:00',
  'Arrival_Time': '13:15',
  'Duration': '6h 15m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 19225},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '3/06/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → BOM → COK',
  'Dep_Time': '07:05',
  'Arrival_Time': '19:00',
  'Duration': '11h 55m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 14924},
 {'Airline': 'Multiple carriers',
  'Date_of_Journey': '21/05/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → HYD → COK',
  'Dep_Time': '07:05',
  'Arrival_Time': '18:10',
  'Duration': '11h 5m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 9646},
 {'Airline': 'Air India',
  'Date_of_Journey': '15/03/2019',
  'Source': 'Banglore',
  'Destination': 'New Delhi',
  'Route': 'BLR → BOM → DEL',
  'Dep_Time': '06:45',
  'Arrival_Time': '15:15',
  'Duration': '8h 30m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 8714},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '18/05/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → BOM → COK',
  'Dep_Time': '20:55',
  'Arrival_Time': '19:00 19 May',
  'Duration': '22h 5m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'In-flight meal not included',
  'Price': 12373},
 {'Airline': 'Air Asia',
  'Date_of_Journey': '6/05/2019',
  'Source': 'Banglore',
  'Destination': 'Delhi',
  'Route': 'BLR → DEL',
  'Dep_Time': '11:10',
  'Arrival_Time': '13:55',
  'Duration': '2h 45m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 3383},
 {'Airline': 'Multiple carriers',
  'Date_of_Journey': '21/03/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → BOM → COK',
  'Dep_Time': '09:00',
  'Arrival_Time': '21:00',
  'Duration': '12h',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 13062},
 {'Airline': 'SpiceJet',
  'Date_of_Journey': '24/03/2019',
  'Source': 'Banglore',
  'Destination': 'New Delhi',
  'Route': 'BLR → DEL',
  'Dep_Time': '05:45',
  'Arrival_Time': '08:35',
  'Duration': '2h 50m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No check-in baggage included',
  'Price': 3527},
 {'Airline': 'IndiGo',
  'Date_of_Journey': '27/05/2019',
  'Source': 'Banglore',
  'Destination': 'Delhi',
  'Route': 'BLR → DEL',
  'Dep_Time': '04:00',
  'Arrival_Time': '06:50',
  'Duration': '2h 50m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 3943},
 {'Airline': 'Air India',
  'Date_of_Journey': '3/05/2019',
  'Source': 'Chennai',
  'Destination': 'Kolkata',
  'Route': 'MAA → CCU',
  'Dep_Time': '11:40',
  'Arrival_Time': '13:55',
  'Duration': '2h 15m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 4667},
 {'Airline': 'Air India',
  'Date_of_Journey': '15/05/2019',
  'Source': 'Kolkata',
  'Destination': 'Banglore',
  'Route': 'CCU → HYD → BLR',
  'Dep_Time': '19:00',
  'Arrival_Time': '11:05 16 May',
  'Duration': '16h 5m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 6117},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '27/06/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → AMD → BOM → COK',
  'Dep_Time': '23:05',
  'Arrival_Time': '19:00 28 Jun',
  'Duration': '19h 55m',
  'Total_Stops': '2 stops',
  'Additional_Info': 'In-flight meal not included',
  'Price': 11150},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '9/03/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → COK',
  'Dep_Time': '11:00',
  'Arrival_Time': '14:15',
  'Duration': '3h 15m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'In-flight meal not included',
  'Price': 7202},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '1/05/2019',
  'Source': 'Kolkata',
  'Destination': 'Banglore',
  'Route': 'CCU → DEL → BLR',
  'Dep_Time': '09:35',
  'Arrival_Time': '10:55 02 May',
  'Duration': '25h 20m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 12121},
 {'Airline': 'IndiGo',
  'Date_of_Journey': '24/03/2019',
  'Source': 'Banglore',
  'Destination': 'New Delhi',
  'Route': 'BLR → DEL',
  'Dep_Time': '22:20',
  'Arrival_Time': '01:10 28 Mar',
  'Duration': '2h 50m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 4377},
 {'Airline': 'IndiGo',
  'Date_of_Journey': '18/06/2019',
  'Source': 'Banglore',
  'Destination': 'Delhi',
  'Route': 'BLR → DEL',
  'Dep_Time': '21:15',
  'Arrival_Time': '00:15 19 Jun',
  'Duration': '3h',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 3943},
 {'Airline': 'Air Asia',
  'Date_of_Journey': '3/04/2019',
  'Source': 'Banglore',
  'Destination': 'Delhi',
  'Route': 'BLR → DEL',
  'Dep_Time': '23:55',
  'Arrival_Time': '02:45 04 Apr',
  'Duration': '2h 50m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 4483},
 {'Airline': 'Jet Airways',
  'Date_of_Journey': '24/03/2019',
  'Source': 'Kolkata',
  'Destination': 'Banglore',
  'Route': 'CCU → BOM → BLR',
  'Dep_Time': '19:45',
  'Arrival_Time': '12:00 25 Mar',
  'Duration': '16h 15m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 14231},
 {'Airline': 'Air India',
  'Date_of_Journey': '01/03/2019',
  'Source': 'Banglore',
  'Destination': 'New Delhi',
  'Route': 'BLR → BOM → AMD → DEL',
  'Dep_Time': '08:50',
  'Arrival_Time': '23:55',
  'Duration': '15h 5m',
  'Total_Stops': '2 stops',
  'Additional_Info': 'No info',
  'Price': 17345},
 {'Airline': 'Vistara',
  'Date_of_Journey': '6/03/2019',
  'Source': 'Chennai',
  'Destination': 'Kolkata',
  'Route': 'MAA → CCU',
  'Dep_Time': '07:05',
  'Arrival_Time': '09:20',
  'Duration': '2h 15m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 7414},
 {'Airline': 'Multiple carriers',
  'Date_of_Journey': '6/05/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → BOM → COK',
  'Dep_Time': '19:00',
  'Arrival_Time': '01:30 07 May',
  'Duration': '6h 30m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 8073},
 {'Airline': 'Vistara',
  'Date_of_Journey': '6/03/2019',
  'Source': 'Mumbai',
  'Destination': 'Hyderabad',
  'Route': 'BOM → DEL → HYD',
  'Dep_Time': '15:40',
  'Arrival_Time': '16:45 07 Mar',
  'Duration': '25h 5m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 12395},
 {'Airline': 'Air India',
  'Date_of_Journey': '6/06/2019',
  'Source': 'Kolkata',
  'Destination': 'Banglore',
  'Route': 'CCU → BOM → BLR',
  'Dep_Time': '09:25',
  'Arrival_Time': '21:50',
  'Duration': '12h 25m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 8366},
 {'Airline': 'Air India',
  'Date_of_Journey': '3/04/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → MAA → COK',
  'Dep_Time': '06:05',
  'Arrival_Time': '09:25 04 Apr',
  'Duration': '27h 20m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 5117},
 {'Airline': 'Multiple carriers',
  'Date_of_Journey': '3/06/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → BOM → COK',
  'Dep_Time': '08:45',
  'Arrival_Time': '19:00',
  'Duration': '10h 15m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 12524},
 {'Airline': 'IndiGo',
  'Date_of_Journey': '15/05/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → BOM → COK',
  'Dep_Time': '15:00',
  'Arrival_Time': '01:30 16 May',
  'Duration': '10h 30m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 7191},
 {'Airline': 'Vistara',
  'Date_of_Journey': '24/05/2019',
  'Source': 'Chennai',
  'Destination': 'Kolkata',
  'Route': 'MAA → CCU',
  'Dep_Time': '07:05',
  'Arrival_Time': '09:20',
  'Duration': '2h 15m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 3687},
 {'Airline': 'IndiGo',
  'Date_of_Journey': '24/06/2019',
  'Source': 'Delhi',
  'Destination': 'Cochin',
  'Route': 'DEL → BOM → COK',
  'Dep_Time': '10:35',
  'Arrival_Time': '21:00',
  'Duration': '10h 25m',
  'Total_Stops': '1 stop',
  'Additional_Info': 'No info',
  'Price': 5894},
 {'Airline': 'Vistara',
  'Date_of_Journey': '24/04/2019',
  'Source': 'Banglore',
  'Destination': 'Delhi',
  'Route': 'BLR → DEL',
  'Dep_Time': '09:45',
  'Arrival_Time': '12:35',
  'Duration': '2h 50m',
  'Total_Stops': 'non-stop',
  'Additional_Info': 'No info',
  'Price': 5403},

In [10]:
DB_NAME = "flight"
COLLECTION_NAME = "flight-Data"
CONNECTION_URL = "mongodb+srv://jahid:jahid@cluster0.gidlt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# above, either remove your credentials or delete the mongoDB resource bofore pushing it to github.

In [11]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

In [12]:
# Uploading data to MongoDB
rec = collection.insert_many(data)

In [13]:
# Load back data from mongodb

df = pd.DataFrame(list(collection.find()))
df.head(5)

,_id,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,674338f696fd7cd5b95f6c25,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,674338f696fd7cd5b95f6c26,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,674338f696fd7cd5b95f6c27,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,674338f696fd7cd5b95f6c28,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,674338f696fd7cd5b95f6c29,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [14]:
if "_id" in df.columns.to_list():
    df = df.drop(columns=["_id"], axis=1)

In [15]:
df.head(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [ ]:
## If you are getting timeout issue

# import certifi
# client = pymongo.MongoClient(CONNECTION_URL, tlsCAFile=certifi.where())
# # TO CREATE THE DATABASE
# data_base = client[DB_NAME]
# collection = data_base[COLLECTION_NAME]
# # TO INSERT DATA INTO THE COLLECTION
# rec = collection.insert_many(data)